name: Build java-trust-store-builder

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch: { }

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build Image "java-trust-store-builder"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push ${{matrix.image}}
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/java-trust-store-builder:latest
